# Generated by Django 5.1.1 on 2024-10-08 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_poll'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.meal')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.poll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('poll', 'user', 'meal')},
            },
        ),
        migrations.AddField(
            model_name='poll',
            name='meals',
            field=models.ManyToManyField(through='items.Vote', to='items.meal'),
        ),
    ]
