# Generated by Django 5.1.1 on 2024-10-09 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_vote_unique_together_remove_vote_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='meals',
        ),
    ]
