# Generated by Django 5.1.1 on 2024-10-10 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_alter_vote_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='object_id',
        ),
        migrations.AddField(
            model_name='vote',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.game'),
        ),
        migrations.AddField(
            model_name='vote',
            name='intendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.intendance'),
        ),
        migrations.AddField(
            model_name='vote',
            name='meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.meal'),
        ),
    ]
