# Generated by Django 5.1.1 on 2024-10-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_remove_vote_content_type_remove_vote_object_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='category',
            field=models.CharField(choices=[('meal', 'Meal'), ('intendancy', 'Intendance'), ('game', 'Game'), ('logistic', 'Logistic')], default='meal', max_length=20),
        ),
    ]
