# Generated by Django 5.1.1 on 2024-10-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_poll_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vote',
            new_name='VoteOption',
        ),
        migrations.RenameField(
            model_name='uservote',
            old_name='vote',
            new_name='vote_option',
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='logistic',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
