# Generated by Django 5.1.1 on 2024-10-11 13:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_remove_voteoption_response_uservote_response_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='uservote',
            unique_together={('user', 'vote_option')},
        ),
    ]
