# Generated by Django 5.1.1 on 2024-10-27 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clairmarais', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='adress',
            new_name='address',
        ),
    ]
