# Generated by Django 5.1.1 on 2024-10-09 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clairmarais', '0005_uservote'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
    ]
