# Generated by Django 5.1.1 on 2024-10-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clairmarais', '0007_remove_poll_meals'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='response',
            field=models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], default='oui', max_length=3),
        ),
    ]
