# Generated by Django 5.1.1 on 2024-10-09 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('clairmarais', '0009_intendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='meal',
        ),
        migrations.AddField(
            model_name='vote',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='vote',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
