# Generated by Django 5.1.1 on 2024-10-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clairmarais', '0010_remove_vote_meal_vote_content_type_vote_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
