# Generated by Django 5.1.1 on 2024-10-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clairmarais', '0014_rename_vote_voteoption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='category',
            field=models.CharField(choices=[('meal', 'Meal'), ('intendance', 'Intendance'), ('game', 'Game'), ('logistic', 'Logistic')], default='meal', max_length=20),
        ),
    ]
