# Generated by Django 5.1.1 on 2024-10-11 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clairmarais', '0015_alter_poll_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voteoption',
            name='response',
        ),
        migrations.AddField(
            model_name='uservote',
            name='response',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voteoption',
            name='logistic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clairmarais.logistic'),
        ),
    ]
