# Generated by Django 5.1.1 on 2024-10-20 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clairmarais', '0018_alter_poll_category_drink'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteoption',
            name='drink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clairmarais.drink'),
        ),
    ]
